### ISSUE TITLE
runautostart这个函数的脚本目录在哪里

### ISSUE THREAD

**Issue by cuicui22** [ayamir/dotfiles#1]
你好
  新版补丁的函数由runAutostart变成了runautostart，请问脚本应该放到那个目录下

**Comment by ayamir** [comment]
这你要自己看新补丁定义的目录是哪里

**Comment by cuicui22** [comment]
不好意思，我是小白，我看你也打得是新补丁，你在哪里定义了目录

**Comment by cuicui22** [comment]
不好意思，我是小白，还有疑问就是我看你也打得新版补丁，他定义的目录在哪，可以自己改吗

**Comment by cuicui22** [comment]
> 不好意思，我是小白，还有疑问就是我看你也打得新版补丁，他定义的目录在哪，可以自己改吗

就是他说的这个$XDG_DATA_HOME是哪里

**Comment by ayamir** [comment]
> > 不好意思，我是小白，还有疑问就是我看你也打得新版补丁，他定义的目录在哪，可以自己改吗
> 
> 就是他说的这个$XDG_DATA_HOME是哪里

echo $XDG_DATA_HOME 看一下输出
