### ISSUE TITLE
Error in message after startup

### ISSUE THREAD

**Issue by rickywu** [ayamir/dotfiles#3]
Windows 10 with default config
packer.nvim: Error running config for nvim-dap: [string "..."]:0: attempt to concatenate a nil value

**Comment by ayamir** [comment]
```shell
cd nord/.config/nvim
git submodule update --recursive
```
Btw, this dotfiles is for linux...

**Comment by rickywu** [comment]
not resolved, vim and nvim should compatible with unix format
