### ISSUE TITLE
怎样使用dotfiles

### ISSUE THREAD

**Issue by jiale-gdyd** [ayamir/dotfiles#4]
我安装好ayamir/nvimdots后，怎样将ayamir/dotfiles将入到nvimdots里面

**Comment by ayamir** [comment]
不懂你在问什么

**Comment by jiale-gdyd** [comment]
就是想將ayamir/dotfiles作爲我的nvim的配置

**Comment by ayamir** [comment]
配nvim你直接去我nvimdots那个仓库不就行了，wiki里面都写好了
