### ISSUE TITLE
nvim配置后出错

### ISSUE THREAD

**Issue by ChristLZS** [ayamir/dotfiles#7]
作者您好～
系统版本：
ubuntu22.04
nvim版本：
`NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info`
按照教程一路安装，最后进入nvim，报错如下：
![截图 2022-09-22 21-07-28](https://user-images.githubusercontent.com/50512605/191755240-881a4fc8-f6d1-4d74-a621-90f2485c86f4.png)
然后输入：“:q”,报错如下：
![截图 2022-09-22 21-06-43](https://user-images.githubusercontent.com/50512605/191755711-bd67a7d4-9600-496e-9220-f6d1f4e53455.png)
后者报错一闪而过，看得不是特别完整，重新安装nvim和重新配置nvim也是一样，有什么思路呢。

**Comment by ayamir** [comment]
你要自己装一下`fzf`

**Comment by ChristLZS** [comment]
感谢作者回复，fzf已安装，反复试了几次还是不行，先不搞了，我们新手还是先用vim吧

**Comment by ayamir** [comment]
重复执行`PackerSync`也不行吗？
