### ISSUE TITLE
yo can you tell me this part 

### ISSUE THREAD

**Issue by Ahmadjerj** [ayamir/dotfiles#9]
![dark-dwm](https://github.com/ayamir/dotfiles/assets/72747814/1aabd9cc-a48e-4ef3-b89e-af0d40f85615)
the thing on the right on the background like the fetch what app and how did you do it? please

**Comment by ayamir** [comment]
https://github.com/brndnmtthws/conky with https://github.com/ayamir/dotfiles/blob/master/nord/.config/conky/conky.conf
